/**
 * Product compile: write embedded version, RR production build, one
 * bun --compile binary for CLI. Stamp: ASTROHACKER_VERSION else package.json.
 *
 * RR server assets live in build/; CLI binary is dist/quikopen.
 * TermSurf server role expects `build/server` present next to package root.
 */
import * as fs from "node:fs";
import * as path from "node:path";

const root = path.resolve(import.meta.dir, "..");
const pkg = JSON.parse(
  fs.readFileSync(path.join(root, "package.json"), "utf8"),
) as {
  version?: string;
};

const overrideVersion = process.env.ASTROHACKER_VERSION?.trim();
const version =
  overrideVersion !== undefined && overrideVersion !== ""
    ? overrideVersion
    : typeof pkg.version === "string"
      ? pkg.version
      : "0.0.1";

const embedPath = path.join(root, "app/cli/embedded-version.ts");
const embedSource = `/**
 * Generated by scripts/build-quikopen.ts at compile time.
 * Do not hand-edit for releases — rebuild with ASTROHACKER_VERSION set.
 */
export const QUIK_EMBEDDED_VERSION = ${JSON.stringify(version)};
`;
fs.writeFileSync(embedPath, embedSource, "utf8");
console.log(`build-quikopen: wrote ${embedPath} = ${version}`);

const rr = Bun.spawnSync(["bun", "run", "build"], {
  cwd: root,
  stdout: "inherit",
  stderr: "inherit",
});
if (rr.exitCode !== 0) {
  process.exit(rr.exitCode);
}

fs.mkdirSync(path.join(root, "dist"), { recursive: true });
try {
  fs.unlinkSync(path.join(root, "dist", "quik-server"));
} catch {
  /* */
}

const compile = Bun.spawnSync(
  [
    "bun",
    "build",
    "--compile",
    "--keep-names",
    "--outfile",
    "dist/quikopen",
    "cli.ts",
  ],
  {
    cwd: root,
    stdout: "inherit",
    stderr: "inherit",
  },
);
if (compile.exitCode !== 0) {
  process.exit(compile.exitCode);
}

const out = path.join(root, "dist", "quikopen");
if (!fs.existsSync(out)) {
  console.error(`build-quikopen: missing ${out}`);
  process.exit(1);
}
console.log(`build-quikopen: wrote ${out}`);
