/** Strict migrated WebBuf rules, shared by all maintained TypeScript. */
import type { DummyRuleMap } from "oxlint";
export const strictTypeScriptRules = {
  "eslint/for-direction": "error",
  "eslint/no-async-promise-executor": "error",
  "eslint/no-case-declarations": "error",
  "eslint/no-compare-neg-zero": "error",
  "eslint/no-cond-assign": "error",
  "eslint/no-constant-binary-expression": "error",
  "eslint/no-constant-condition": "error",
  "eslint/no-control-regex": "error",
  "eslint/no-debugger": "error",
  "eslint/no-delete-var": "error",
  "eslint/no-dupe-else-if": "error",
  "eslint/no-duplicate-case": "error",
  "eslint/no-empty": "error",
  "eslint/no-empty-character-class": "error",
  "eslint/no-empty-pattern": "error",
  "eslint/no-empty-static-block": "error",
  "eslint/no-ex-assign": "error",
  "eslint/no-extra-boolean-cast": "error",
  "eslint/no-fallthrough": "error",
  "eslint/no-global-assign": "error",
  "eslint/no-invalid-regexp": "error",
  "eslint/no-irregular-whitespace": [
    "error",
    {
      skipComments: false,
      skipJSXText: false,
      skipRegExps: false,
      skipStrings: true,
      skipTemplates: false,
    },
  ],
  "eslint/no-loss-of-precision": "error",
  "eslint/no-misleading-character-class": "error",
  "eslint/no-nonoctal-decimal-escape": "error",
  "eslint/no-prototype-builtins": "error",
  "eslint/no-regex-spaces": "error",
  "eslint/no-self-assign": "error",
  "eslint/no-shadow-restricted-names": "error",
  "eslint/no-sparse-arrays": "error",
  "eslint/no-unexpected-multiline": "error",
  "eslint/no-unsafe-finally": "error",
  "eslint/no-unsafe-optional-chaining": "error",
  "eslint/no-unused-labels": "error",
  "eslint/no-unused-private-class-members": "error",
  "eslint/no-useless-backreference": "error",
  "eslint/no-useless-catch": "error",
  "eslint/no-useless-escape": "error",
  "eslint/require-yield": "error",
  "eslint/use-isnan": "error",
  "eslint/valid-typeof": "error",
  "eslint/no-var": "error",
  "eslint/prefer-const": "error",
  "eslint/prefer-rest-params": "error",
  "eslint/prefer-spread": "error",
  "typescript/await-thenable": "error",
  "typescript/ban-ts-comment": [
    "error",
    {
      minimumDescriptionLength: 10,
    },
  ],
  "eslint/no-array-constructor": "error",
  "typescript/no-array-delete": "error",
  "typescript/no-base-to-string": "error",
  "typescript/no-confusing-void-expression": "error",
  "typescript/no-deprecated": "error",
  "typescript/no-duplicate-enum-values": "error",
  "typescript/no-duplicate-type-constituents": "error",
  "typescript/no-dynamic-delete": "error",
  "typescript/no-empty-object-type": "error",
  "typescript/no-explicit-any": "error",
  "typescript/no-extra-non-null-assertion": "error",
  "typescript/no-extraneous-class": "error",
  "typescript/no-floating-promises": "error",
  "typescript/no-for-in-array": "error",
  "typescript/no-implied-eval": "error",
  "typescript/no-invalid-void-type": "error",
  "typescript/no-meaningless-void-operator": "error",
  "typescript/no-misused-new": "error",
  "typescript/no-misused-promises": "error",
  "typescript/no-misused-spread": "error",
  "typescript/no-mixed-enums": "error",
  "typescript/no-namespace": "error",
  "typescript/no-non-null-asserted-nullish-coalescing": "error",
  "typescript/no-non-null-asserted-optional-chain": "error",
  "typescript/no-non-null-assertion": "error",
  "typescript/no-redundant-type-constituents": "error",
  "typescript/no-require-imports": "error",
  "typescript/no-this-alias": "error",
  "typescript/no-unnecessary-boolean-literal-compare": "error",
  "typescript/no-unnecessary-condition": "error",
  "typescript/no-unnecessary-template-expression": "error",
  "typescript/no-unnecessary-type-arguments": "error",
  "typescript/no-unnecessary-type-assertion": "error",
  "typescript/no-unnecessary-type-constraint": "error",
  "typescript/no-unnecessary-type-conversion": "error",
  "typescript/no-unnecessary-type-parameters": "error",
  "typescript/no-unsafe-argument": "error",
  "typescript/no-unsafe-assignment": "error",
  "typescript/no-unsafe-call": "error",
  "typescript/no-unsafe-declaration-merging": "error",
  "typescript/no-unsafe-enum-comparison": "error",
  "typescript/no-unsafe-function-type": "error",
  "typescript/no-unsafe-member-access": "error",
  "typescript/no-unsafe-return": "error",
  "typescript/no-unsafe-unary-minus": "error",
  "eslint/no-unused-expressions": "error",
  // Match typescript-eslint defaults, not Oxlint's implicit ^_ ignore pattern.
  "eslint/no-unused-vars": [
    "error",
    { caughtErrors: "all", reportVarsOnlyUsedAsTypes: true },
  ],
  "eslint/no-useless-constructor": "error",
  "typescript/no-wrapper-object-types": "error",
  "typescript/only-throw-error": "error",
  "typescript/prefer-as-const": "error",
  "typescript/prefer-literal-enum-member": "error",
  "typescript/prefer-namespace-keyword": "error",
  "typescript/prefer-promise-reject-errors": "error",
  "typescript/prefer-reduce-type-parameter": "error",
  "typescript/prefer-return-this-type": "error",
  "typescript/related-getter-setter-pairs": "error",
  "typescript/require-await": "error",
  "typescript/restrict-plus-operands": [
    "error",
    {
      allowAny: false,
      allowBoolean: false,
      allowNullish: false,
      allowNumberAndString: false,
      allowRegExp: false,
    },
  ],
  "typescript/restrict-template-expressions": [
    "error",
    {
      allowAny: false,
      allowBoolean: false,
      allowNever: false,
      allowNullish: false,
      allowNumber: false,
      allowRegExp: false,
    },
  ],
  "typescript/return-await": ["error", "error-handling-correctness-only"],
  "typescript/triple-slash-reference": "error",
  "typescript/unbound-method": "error",
  "typescript/unified-signatures": "error",
  "typescript/use-unknown-in-catch-callback-variable": "error",
  "typescript/adjacent-overload-signatures": "error",
  "typescript/array-type": "error",
  "typescript/ban-tslint-comment": "error",
  "typescript/class-literal-property-style": "error",
  "typescript/consistent-generic-constructors": "error",
  "typescript/consistent-indexed-object-style": "error",
  "typescript/consistent-type-assertions": "error",
  "typescript/consistent-type-definitions": "error",
  "typescript/dot-notation": "error",
  "typescript/no-confusing-non-null-assertion": "error",
  "eslint/no-empty-function": "error",
  "typescript/no-inferrable-types": "error",
  "typescript/non-nullable-type-assertion-style": "error",
  "typescript/prefer-find": "error",
  "typescript/prefer-for-of": "error",
  "typescript/prefer-function-type": "error",
  "typescript/prefer-includes": "error",
  "typescript/prefer-nullish-coalescing": "error",
  "typescript/prefer-optional-chain": "error",
  "typescript/prefer-regexp-exec": "error",
  "typescript/prefer-string-starts-ends-with": "error",
} satisfies DummyRuleMap;
